apiVersion: apps/v1
kind: Deployment
metadata:
  name: idle-deployment
  namespace: energy
spec:
  selector:
    matchLabels:
      app: idle
  replicas: 1
  template:
    metadata:
      labels:
        app: idle
    spec:
      containers:
      - name: idle
        image: davidfreina/sleep:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: SLEEP_TIME
          value: "120"
