apiVersion: v1
kind: Pod
metadata:
  name: single-cpu-pod
  namespace: energy
spec:
    containers:
    - name: fibonacci
      image: davidfreina/fib:latest
      imagePullPolicy: Never
      env:
      - name: "N"
        value: "49"
    restartPolicy: Never