apiVersion: v1
kind: Pod
metadata:
  name: multi-cpu-pod
  namespace: energy
spec:
    containers:
    - name: fibonacci-openmp
      image: davidfreina/fib_n:latest
      imagePullPolicy: Never
      env:
      - name: "N"
        value: "37"
    restartPolicy: Never
