apiVersion: apps/v1
kind: Deployment
metadata:
  name: single-disk-deployment
  namespace: energy
spec:
  selector:
    matchLabels:
      app: hdparm
  replicas: 1
  template:
    metadata:
      labels:
        app: hdparm
    spec:
      containers:
      - name: hdparm
        image: davidfreina/disk:latest
        imagePullPolicy: Never
        env:
        - name: N
          value: "40"
