---
extraEnvVars:
  KEPLER_LOG_LEVEL: "2"
  # METRIC_PATH: "/metrics"
  # BIND_ADDRESS: "0.0.0.0:9102"
  ENABLE_GPU: "false"
  ENABLE_QAT: "false"
  ENABLE_EBPF_CGROUPID: "false"
  EXPOSE_HW_COUNTER_METRICS: "false"
  EXPOSE_IRQ_COUNTER_METRICS: "false"
  EXPOSE_CGROUP_METRICS: "false"
  ENABLE_PROCESS_METRICS: "false"
  CPU_ARCH_OVERRIDE: "x86-64"
  CGROUP_METRICS: '*'
  # REDFISH_PROBE_INTERVAL_IN_SECONDS: "60"
  # REDFISH_SKIP_SSL_VERIFY: "true"

serviceMonitor:
  enabled: false
  namespace: ""
  interval: 30s
  scrapeTimeout: 5s
  labels: {}
  attachMetadata:
    node: false
  relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
        - __meta_kubernetes_pod_node_name
      targetLabel: instance

redfish:
  enabled: false
  name: redfish
  labels: {}
  annotations: {}
  fileContent: |-
    your_kubelet_node1_name,redfish_username,redfish_password,https://node1_redfish_ip_or_hostname
    your_kubelet_node2_name,redfish_username,redfish_password,https://node2_redfish_ip_or_hostname
